### PR TITLE
docs: delete duplicate.

### PR DESCRIPTION
**Pull request by hu-qi**
## What is the purpose of the change

= Delete duplicate.

## Brief change log

-   No changes.

## Checklist

-   **Are tests written for added code?**
    
    -   [ ] Yes
    -   [ √] No because: Just doc-file.

-   **Did you introduce any new dependencies?**
    
    -   [ √] No
    -   [ ] Yes
        -   Dependency:
        -   Reason:

### CODE REVIEW

**Review by heming6666 — APPROVED** [review]
LGTM

**Comment by heming6666** [comment]
Thank you @hu-qi for your contribution!  But you need sign our Contributor License Agreement before we can merge your contribution.

You can click here to sign our CLA.

image

**Comment by hu-qi** [comment]
> Thank you @hu-qi for your contribution! But you need sign our Contributor License Agreement before we can merge your contribution.
> 
> You can click here to sign our CLA.
> 
> image

Thanks！

**Pull request merged**
